# Generated by Django 3.1.7 on 2021-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1_app', '0002_auto_20210401_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
