# Generated by Django 3.1.7 on 2021-04-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1_app', '0003_auto_20210401_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noodle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
